### ISSUE TITLE
Fixed anchors independant from world understanding

### ISSUE THREAD

**Issue by ghost** [immersive-web/anchors#3]
From the explainer "Anchors update as real-world understanding improves". We might want to leave the option to the developer for such updates. If the experience is about to place objects relative to each other, having one object's pose update while the second one doesn't might mess up with the system representation (think assembling a puzzle with different parts all having a pose).
This problem might be solved by setting an initial pose and then adding objects relative to it, but there might be use cases where that wouldn't work

**Comment by blairmacintyre** [comment]
I understand your motivation, but I don't think this is the right solution.

Anchors are, by definition, supposed to correspond to real-world locations.  All of the current tracking systems, and any foreseeable ones in the future, will need to adjust anchors as their understanding of the world changes.

There is no implication that every piece of content needs to be attached directly to an anchor;  all content should be rooted at some anchor, but the content attached to some anchor might be large.
 
If a developer wants to attach a collection of content to a coordinate system some place in the world, and they need the relationships between those bits of content to remain static, they should attach the entire scene to one anchor.

So, for the puzzle example:  If I attach two ends of a puzzle to two anchors, and the system updates the poses of those anchors as it's knowledge of the world changes, as a developer you have the option to:
- ignore this, which you can easily do by rooting all the content to one of the two anchors (perhaps switching between the two anchors as the user moves around, if you want).
- adjust the puzzle content, such as by scaling the scene to remain between the anchors, but have the same relative relationships
- adjust the puzzle content based on the new relationships.

In the end, you are free to do what you want.  But the concept of an anchor, as tightly coupled to the world, is clean and simple, and it's important that developers are intentional about how they want to deal with the inherent messiness of real-world tracking.

We should add a discussion of this to any spec for anchors!

**Comment by ghost** [comment]
Yeah, you're right, I feel like there might be some trouble but I don't manage to put the finger on it for now.

Does the real world understanding triggering update system includes the environment changing? Let's say I put a model on the floor intersection, then put a real chair at this exact spot, should the model update to match the chair recast as the system detects the chair? (maybe that's for an other discussion)

**Comment by judax** [comment]
The anchor proposal's scope is pretty narrow as no proposal for world understanding apart from hit test has been made thus far. Anchors could in the future be associated to an element inferred from the real world (a chair, a marker, a face, ...) and because of that, the anchor should also be updated as the element moves.

Some good practices on how to use anchors would be very helpful. Although in general I agree with Blair that anchors should be world objects only, specifying only one for a large model/world, could still be problematic and most likely, more than one anchor could be a better solution to lower the drift that can occur while moving larger distances.

**Comment by ghost** [comment]
Without including world understanding, if I put an object on the floor at 0 height, then move an object there, the hit test now collide at height 0.5 at the exact same height, should it update the position of the object positioned there? The system wouldn't need to know what object has moved there, just that now the height at this position is 0.5

**Comment by blairmacintyre** [comment]
@judax I agree that my "one anchor for all the content" suggestion is not ideal.  I was merely pointing out that this is a valid option for a programmer would doesn't want to deal with relationships between content changing.  It's problematic, but there is no way we could prevent it from being done.  Devs will learn over time when and why this is problematic, and when they can do it.  

@tbalouet The position will not be updated.  The anchor is, in this case, on the floor.  When more world info is exposed in the future (and it will be, I am pretty sure), an app could deal with this in various ways depending on their needs and preferences:  if there is a mesh/plane-set (like hololens, arkit, arcore), the app could detect if anchors are "hidden" and decide to manage it (by creating a new anchor on the object, at 0.5 in this example;  by just hiding the content temporarily, by asking the user to fix the world(!), etc).

**Comment by judax** [comment]
@tbalouet if I understand correctly, when you are referring to "object" in your reply, you mean a real world object right? Tracking of real world objects is out of the scope of the current proposal. If you want to constantly update an object you could perform a continuous hit test against that location. In the future it might be possible to have such concept of tracking things, but not currently, the main reason being simplicity and that arbitrary pose anchors are always needed anyway. Should you create an anchor for each hit? Well, that depends on your need. If you rely on the hit to place the virtual object, then you may not need an anchor. But if you are thinking about placing the virtual object in a hit for a prolonged period of time without updating it yourself, then you may require an anchor. We will create a new issue to comment on how lightweight anchor creation should be in order to enable easy and fast creation/destruction of them.

**Comment by ghost** [comment]
I meant a virtual object in that example. But I guess Blair answered my question, where the update on the world information and modifying things on its understanding should be done on the app level.

**Comment by thetuvix** [comment]
For HoloLens, we'd documented a set of [spatial anchor best practices](https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-anchors) to help developers reason about when to create new anchors and when to share existing anchors.

One of those best practices is "[Group holograms that should form a rigid cluster](https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-anchors#group-holograms-that-should-form-a-rigid-cluster)".  As @blairmacintyre points out, it's up to an app to decide what parts of their scene must adjust together as a solid block, and what other parts of the scene may adjust independently to maximize fidelity to the physical world.

I agree that we should narrowly dedicate anchors here to tracking a physical location in the world as accurately as possible.  An app that wishes to repeat a raycast from the same perspective on some cadence is free to do so.  In the future, if tracking systems support tracking physical objects like chairs more explicitly, we could let apps decide that their anchor should be attached to that hit-tested chair over time, rather than fixed to that point in free space.  In any of those cases, apps would provide for any rigid child transforms underneath an anchor as model transforms in whatever 3D web framework they choose to use on top of WebXR.

As a side note, it's interesting how some engineering problems from the physical world start to resurface now in the virtual world:  Imagine a virtual bridge that spans between two physical tables that are 10m apart.  The app may choose to pin each side of the bridge to its own anchor to maximize stability where the bridge meets each table.  If so, the app's bridge model will then need to accommodate slight changes in the length of the bridge over time, just as real bridges do using expansion joints!

**Comment by bialpio** [comment]
Closing old issue. Current explainer and the specification draft treats anchors as fixed relative to the real world. Please open a new issue if you disagree with this approach.
