### ISSUE TITLE
Encourage developers to pass in a XRHitResult rather than a raw matrix

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/anchors#6]
Ideally, developers always create anchors based on a XRHitResult object if they got the location using that API, since the hit-result may have a connection to a trackable object. We can create much higher quality anchors if we have access to the underlying trackable object and we want to create a well of success for developers so the best and easiest ways of using the API are the same.

This is tricky given that we want to support arbitrary poses - how do we ensure that developers use the right API if there are two options?

**Comment by TrevorFSmith** [comment]
One approach would be to indicate that anchors are desired when performing the hit-test and then each XRHitResult would (if possible) be returned with an associated Anchor.

**Comment by TrevorFSmith** [comment]
Based on conversation in today's AR call, it sounds like there's a general need for two methods for creating an anchor, one that takes an arbitrary point in space and one that takes an XRHitResult.

**Comment by judax** [comment]
Creating an anchor for each hit result does not seem like a great idea. Although anchors are pretty lightweight, we are talking about the possibility of at least creating an anchor per frame (if not more). The math involved to keep anchors alive is not complex but still adds burden to the underlying system, specially when hundreds if not thousands of anchors could be created.

I do not think there is a way to enforce the use XRHitResult to create an anchor, and there should not be because I think we are at least in an agreement that there needs to be an arbitrary anchor creation API because there are use cases for them (HUDs, floating characters, improved accuracy over time/space, ...). So the options I see are:

1. Provide 2 methods in session to create anchors. One with an arbitrary pose and another with an XRHitResult.
2. XRHitResult provides a method to create an anchor from it. ARCore, for example, uses this API ergonomics as Alex Turner from MSFT pointed out: https://developers.google.com/ar/reference/java/com/google/ar/core/HitResult.html#createAnchor()
3. Instead of allowing to pass an arbitrary pose, the API allows the developer to instantiate an XRHitResult instance passing a pose. This way, the session API just has one method to create anchors based on XRHitResult.

I added the third option ir order to at least have the discussion that not allowing developer to do the "wrong" thing (creating an anchor using the pose of the XRHitResult instead of the XRHitResult itself) is what we want to ensure, then there is an option. But I very much dislike the idea of allowing developer to create XRHitResult instances.

Also, 1 and 2 could coexist in the same API although I think is better to provide just one or the other.

Anyway, what do you think?

**Comment by blairmacintyre** [comment]
I too agree that both methods (from hittestresult, from matrix) are probably best.

Your method (2) may be needed  since some systems (ARCore, for example) support it and presumably can "do better" than just creating from a matrix. It is not clear that most systems would support something like this (ARKit, for example, does not, I don't  think), but that's fine.  However, developers might not use it at all if there are two ways of creating an anchor from a hit test.  

So as you suggest, I'd vote for a way to create anchors from a matrix, and then a method on hittestresult that creates it as in (2) ...

**Comment by lincolnfrog** [comment]
Two points: 
1) just to clarify, I didn't mean to imply that we would automatically create anchors for every hit result. i re-read the wording of the issue and see how it could be interpreted that way. I meant ideally developers would always create an anchor from a XRHitResult IFF they actually wanted to track that location because they placed an object.

2) I actually think there is some merit to your option (3) - what if we reimagined XRHitResult as XRPose - then it would be a lot less weird to have only one API for creating anchors and allow the developer to create their own XRPoses from arbitrary data. The XRPose would also need to have a "relativeObject" attribute, which would need to support being a XRTrackable or whatever that representation eventually becomes. @toji and I had a conversation today about XRHitResult needing to have a getMatrix(XRCoordinateSystem) API instead of just a .matrix property to support getting the result in various coordinate systems. We could move towards a more globally-useful XRPose object that has a getMatrix(XRCoordinateSystem) and an optional relative object and it could be used for hit results and much, much more.

**Comment by judax** [comment]
@lincolnfrog my comment about creating anchors per hit result was replying to the comment from @TrevorFSmith but now that I have re-read the comment, I think what he was proposing was to be able to specify in the hit test call that if a hit is found, an anchor is returned for the hit. I still think it would imply that more anchors than most likely are necessary will be created and then the developer should remove/destroy them (or manually set them to be added to the session, which still means the same thing). If I am misunderstanding something, please, do not hesitate to elaborate on the idea.

About your proposal @lincolnfrog of using XRPose, what about inheritance (I know is recommended not to abuse it) and make XRHitResult to extend XRPose and then allow the future trackable attribute to be in the derived class? This way, adding an anchor would receive an XRPose that could be an arbitrary one or an XRHitResult. I think that the right concept is to say that an XRHitResult has an XRPose, rathe than is an XRPose. Even in this case, I think the XRPose obtained from the XRHitResult could be interpreted internally differently as an XRPose create arbitrarily, similar to what is happening with XRCoordinateSystems for the hit test API to specify what the hit test ray is relative to.

@blairmacintyre I think is better not to have 2 methods for the same thing. Still, as you mention, even though the ARCore API provides the anchor creation functionality from a hit result, implementing this in systems that do not have that functionality (and even not having it on ARCore based systems) should not be a problem, just an implementation detail to be resolved by the UA AFAICT.

**Comment by lincolnfrog** [comment]
@judax I like your suggestion of having XRHitResult inherit from XRPose - seems like the best of both worlds. Is there an education issue with developers not necessarily realizing what they have is usable in the createAnchor(XRPose) API?

**Comment by bialpio** [comment]
One consideration of having XRHitResult inherit from XRPose is that this approach would require the API implementers to check the type passed in to `createAnchor()` at run-time, and potentially use different logic depending on the result of the check. This underlying logic might be different based on the type of the passed in object (anchors created from hit test result might behave differently than others), and might not be immediately obvious to the users of the API (it will be only apparent by reading the spec, despite the fact that we should be able to express it directly in the API). I like the approach described in 2) above - added benefit is that it naturally extends to other types that can have anchors created out of them:

```
XRSession.createAnchor(XRPose, XRSpace);
XRHitResult.createAnchor(XRPose, XRSpace);
XRPlane.createAnchor(XRPose, XRSpace);
```

Also, it might be worth noting here that ARCore [describes](https://developers.google.com/ar/reference/java/arcore/reference/com/google/ar/core/HitResult#createAnchor()) `hitResult.createAnchor()` only as a convenience for `hitResult.getTrackable().createAnchor(hitResult.getHitPose())`.

**Comment by bialpio** [comment]
Closing old issue. In the current specification draft, I decided to go with the 2 following methods:
```
XRFrame.createAnchor(XRPose, XRSpace);
XRHitTestResult.createAnchor(XRPose);
```

XRFrame needs to take both pose and the space relative to which the pose is expressed, and will create a "free-floating" anchor that will attempt to maintain its relationship to the real world. XRHitTestResult does not need to accept the space since the pose is implicitly treated as expressed relative to the hit test result.

Please reopen the issue or file a new one if you disagree with this approach.
